baseurl = "https://recyclebin.zip/"
languageCode = "en-us"
theme = "terminal"
ignoreLogs = ['warning-goldmark-raw-html']

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false
  showLastUpdated = false

[languages]
  [languages.en]
    title = "Recyclebin.zip"
    subtitle = "All the posts you were about to delete, nicely zipped up"
    keywords = "Blog, cyber security, security, infosec, cybersecurity, cloud security, technology, IT security"
    copyright = "©Guillaume Ross"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"
    disableAliases = true
    pagerSize = 10
    path = 'page'

    [languages.en.params.logo]
      logoText = "Recyclebin.zip"
      logoHomeLink = "/"

    [languages.en.menu]
        [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/posts/index.xml"